"""
Django settings for workflow-engine project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
import os
# 强制使用 pytz 兼容层
import pytz
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
import django.db.models.fields

try:
    import timezone_field.fields
    if not hasattr(timezone_field.fields.TimeZoneField, 'CHOICES'):
        # 伪造一个 CHOICES，防止 django-celery-beat 在 Admin 渲染时崩溃
        new_choices = [(tz, tz) for tz in pytz.common_timezones]
        timezone_field.fields.TimeZoneField.CHOICES = new_choices
        # print(f"已为 TimeZoneField 添加 CHOICES 属性 {new_choices}，兼容 django-celery-beat Admin 界面。")
except ImportError:
    # 如果 timezone_field 没有安装，直接跳过，不影响其他功能
    pass

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# print(f"项目根目录 BASE_DIR: {BASE_DIR}")
# 1. 开启国际化
USE_I18N = True
USE_L10N = True

# 2. 设置默认语言
LANGUAGE_CODE = 'zh-hans' # 默认中文

# 3. 定义可选语言列表
LANGUAGES = [
    ('zh-hans', _('中文')),
    ('en', _('English')),
]

LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_SECURE = False  # 本地 http 环境必须为 False

# 4. 配置翻译文件存放路径（在项目根目录创建 locale 文件夹）
import os
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# 允许使用邮件登录的配置
AUTHENTICATION_BACKENDS = [
    'api_services.backends.EmailBackend',        # 优先使用邮件认证
    'django.contrib.auth.backends.ModelBackend', # 备用：保留原生用户名认证
]

# 登录后的跳转地址
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/subs/subs_manage/'
LOGOUT_REDIRECT_URL = '/login/'

#密码复杂度校验 (防止用户设置 123456)
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 8}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

os.environ['PYTZ_DEPRECATION_SHIM'] = '0' # 某些环境下需要屏蔽警告


GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "your-gemini-api-key")
GITHUB_API_KEY = os.environ.get("GITHUB_API_KEY", "your-github-api-key")
TKH_N8N_API_KEY = os.environ.get("TKH_N8N_API_KEY", "your-tkh-n8n-api-key")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h@dv@mson#j()9)5le9t7@56-w6n(u7yw5*u3*0e5a6bkpza$m'


# Application definition
API_VERSION = 'v1'
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'corsheaders',
    'rosetta', #多语言界面对照表
    'ai_subscription', #AI简报订阅管理
    'api_services', #自定义API服务和用户设置，权限验证
    'approve_flow', #审批流管理模块
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 你的自定义门禁中间件
    'api_services.middleware.LoginRequiredMiddleware', 
]

# 允许所有外部域名调用你的 API (或者你可以指定特定白名单)
CORS_ALLOW_ALL_ORIGINS = True 
# CORS_ALLOWED_ORIGINS = ["https://client1.com", "https://client2.com"] # 白名单模式

ROOT_URLCONF = 'workflow-engine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            str(BASE_DIR) + '/workflow-engine/htmls',
            str(BASE_DIR) + '/ai_subscription/templates',
            str(BASE_DIR) + '/api_services/templates',
            str(BASE_DIR) + '/approve_flow/templates',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
            # 添加下面这个 'builtins' 配置
            'libraries': {
                'i18n': 'django.templatetags.i18n',
            },
            'builtins': [
                'django.templatetags.i18n', # 这样所有页面都可以直接用 {% trans %}
            ],            
        },
    },
]

WSGI_APPLICATION = 'workflow-engine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
                    # 设置 20 秒超时，减少 "locked" 报错
                    'timeout': 20,
                    # 开启 WAL 模式（预写日志），大幅提升并发能力
                    'init_command': "PRAGMA journal_mode=WAL;",
                },        
    },
    # 业务库：PostgreSQL（可通过环境变量覆盖）
    'business': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('BUSINESS_DB_NAME', 'workflow_business'),
        'USER': os.getenv('BUSINESS_DB_USER', 'postgres'),
        'PASSWORD': os.getenv('BUSINESS_DB_PASSWORD', ''),
        'HOST': os.getenv('BUSINESS_DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('BUSINESS_DB_PORT', '5432'),
        'CONN_MAX_AGE': 60,
        'ATOMIC_REQUESTS': False,
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

USE_TZ = True
# 2. 强制 Celery 使用 pytz
TIME_ZONE = 'Asia/Shanghai'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_ENABLE_UTC = False
# 3. 告诉 django-celery-beat 不要尝试读取系统时区
USE_DEPRECATED_PYTZ = True
DJANGO_CELERY_BEAT_TZ_AWARE = not USE_DEPRECATED_PYTZ


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# 静态文件 URL 前缀
STATIC_URL = '/static/'

# 额外的静态文件查找路径
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# 执行 collectstatic 时文件汇总的目录（生产环境使用）
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 1. 用户访问上传文件的 URL 前缀
# 浏览器中显示的路径将以 /media/ 开头
MEDIA_URL = '/media/'

# 2. 文件在服务器磁盘上的实际存储路径
# BASE_DIR 是项目的根目录，这将在项目根目录下创建一个 media 文件夹
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# AI Skills Catalog 文件路径，提供给 AI 函数调用作为选择 skill 的参考
SKILLS_CATALOG_PATH = os.path.join(BASE_DIR, 'skills_docs', 'SKILLS_CATALOG.md')

#告诉 Celery Beat 每隔多久巡检一次数据库
CELERY_BEAT_SCHEDULE = {
    # 任务名称（自定义）
    'dispatch-ai-reports-every-hour': {
        # 指向你的 task 函数路径
        'task': 'ai_subscription.tasks.dispatch_periodic_reports',
        # 每半个时运行一次 (1800秒)
        # 也可以使用 crontab(minute=0, hour='*') 实现整点运行
        'schedule': 1800, 
    },
}

# 指定使用数据库作为调度器存储
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# 必须显式指定使用 redis
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
# 建议加上这行，防止 kombu 尝试连接 amqp
CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
# 增加下面这一行，防止连接超时过快
CELERY_BROKER_CONNECTION_TIMEOUT = 30

# UserScheduledTask 附件参数自动映射配置
# 精确参数名命中（优先）
TASK_ATTACHMENT_PARAM_NAMES = [
    'attachments',
    'attachment',
    'files',
    'file_paths',
    'docs',
    'documents',
]

# 参数名关键字模糊命中（兜底）
TASK_ATTACHMENT_PARAM_KEYWORDS = [
    'attachment',
    'file',
    'doc',
]

GOOGLE_OAUTH_SCOPES=["https://www.googleapis.com/auth/userinfo.email",
  "https://www.googleapis.com/auth/userinfo.profile",
  'https://www.googleapis.com/auth/peopleapi.readonly',
  "https://www.googleapis.com/auth/spreadsheets",
  "https://www.googleapis.com/auth/documents",
  "https://www.googleapis.com/auth/drive",
  "https://www.googleapis.com/auth/drive.file",
  "https://www.googleapis.com/auth/gmail.compose",
  "https://www.googleapis.com/auth/gmail.modify",
  'https://www.googleapis.com/auth/gmail.send',
  "https://mail.google.com/",
  "https://www.googleapis.com/auth/script.scriptapp"
  ]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# === DYNAMIC SETTINGS START (managed via UI) ===
# 请勿手动编辑 START/END 标记之间的内容，避免破坏自动更新。
DYNAMIC_SETTINGS = {}
for _k, _v in DYNAMIC_SETTINGS.items():
    globals()[_k] = _v
# === DYNAMIC SETTINGS END ===