# Generated by Django 6.0.2 on 2026-02-23 03:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('role_code', models.CharField(max_length=50, unique=True, verbose_name='角色代码')),
                ('description', models.TextField(blank=True, verbose_name='职责描述')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '角色定义',
                'verbose_name_plural': '角色定义管理',
                'ordering': ['role_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', '提交申请'), ('SKIP', '流程跳转'), ('APPROVE', '审批通过'), ('REJECT', '审批驳回'), ('NOTIFY', '流程通知'), ('TRANSFER', '任务转办'), ('RETURN', '打回重做'), ('CANCEL', '取消审批'), ('FINISH', '审批结束')], max_length=20, verbose_name='操作动作')),
                ('is_returned', models.BooleanField(default=False, verbose_name='是否打回重做')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审批日志',
                'verbose_name_plural': '审批日志',
                'ordering': ['instance', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval_Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='approval_attachments/', verbose_name='附件文件')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名称')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='approve_flow.approvallog', verbose_name='审批日志')),
            ],
            options={
                'verbose_name': '审批附件',
                'verbose_name_plural': '审批附件管理',
            },
        ),
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='审核步骤', max_length=100, verbose_name='环节名称')),
                ('level', models.IntegerField(default=0, verbose_name='审批层级')),
                ('order', models.IntegerField(default=0, verbose_name='审批顺序')),
                ('approve_mode', models.CharField(choices=[('ALL', '会签'), ('ANY', '或签'), ('NOTIFY', '仅通知')], max_length=10, verbose_name='审批模式')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PROCESSING', '审批中'), ('COMPLETED', '已完成'), ('SKIPPED', '已跳过')], default='PENDING', max_length=20, verbose_name='节点状态')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='进入环节时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='离开环节时间')),
                ('approvers', models.ManyToManyField(blank=True, related_name='approval_nodes', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '审批实例节点',
                'verbose_name_plural': '审批实例节点',
                'ordering': ['instance', 'level', 'order'],
            },
        ),
        migrations.AddField(
            model_name='approvallog',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approve_flow.approvalnode', verbose_name='审批环节'),
        ),
        migrations.CreateModel(
            name='ApproveWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='唯一标识，例如：AI_SUB_001', max_length=50, unique=True, verbose_name='流程编码')),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('description', models.TextField(blank=True, verbose_name='流程描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '审批流程',
                'verbose_name_plural': '审批流程',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='部门名称')),
                ('dept_code', models.CharField(max_length=50, unique=True, verbose_name='部门代码')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='approve_flow.department', verbose_name='上级部门')),
                ('manager_role', models.ForeignKey(blank=True, help_text='关联角色定义表，确定该部门的主管岗位', null=True, on_delete=django.db.models.deletion.SET_NULL, to='approve_flow.roledefinition', verbose_name='负责人角色')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门管理',
            },
        ),
        migrations.CreateModel(
            name='BusinessObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='业务索引ID')),
                ('business_code', models.CharField(help_text='用于和业务模块的原始单据进行关联索引', max_length=100, unique=True, verbose_name='单据编号')),
                ('business_description', models.CharField(blank=True, help_text='用于业务单据的简单描述，方便审批人快速了解单据内容', max_length=500, null=True, verbose_name='业务描述')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='业务金额')),
                ('permission_tag', models.CharField(blank=True, max_length=500, verbose_name='权限标识')),
                ('status', models.CharField(choices=[('CREATED', '创建'), ('PROGRESS', '审批中'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('CANCELLED', '已取消')], default='CREATED', max_length=20, verbose_name='单据状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批完成时间')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='驳回时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_obj_applicants', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='业务类型')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='approve_flow.approveworkflow', verbose_name='审批流程')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approve_flow.department', verbose_name='申请部门')),
            ],
            options={
                'verbose_name': '业务审批单',
                'verbose_name_plural': '业务审批单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROCESSING', '审批中'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('CANCELLED', '已取消')], db_index=True, default='PROCESSING', max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('is_finished', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('current_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_instances', to='approve_flow.approvalnode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approve_flow.approveworkflow')),
            ],
            options={
                'verbose_name': '审批实例',
                'verbose_name_plural': '审批实例',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='approve_flow.flowinstance', verbose_name='流程实例'),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='approve_flow.flowinstance', verbose_name='流程实例'),
        ),
        migrations.CreateModel(
            name='NodeApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, verbose_name='岗位角色')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='审批人邮箱')),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('NOTIFIED', '已通知'), ('COMPLETED', '已处理'), ('SKIPPED', '已跳过')], default='PENDING', max_length=20, verbose_name='个人状态')),
                ('order', models.IntegerField(default=0, verbose_name='显示排序')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('instance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='approver_details', to='approve_flow.flowinstance', verbose_name='流程实例')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_details', to='approve_flow.approvalnode', verbose_name='流程步骤')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '节点审批明细',
                'verbose_name_plural': '节点审批明细',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='approvallog',
            name='node_approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='approve_flow.nodeapprover', verbose_name='审批明细'),
        ),
        migrations.CreateModel(
            name='OrgHier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='职位名称')),
                ('is_approver', models.BooleanField(default=False, verbose_name='是否审批人')),
                ('rank_level', models.PositiveIntegerField(default=3, verbose_name='职级权重')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approve_flow.department', verbose_name='所属部门')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='直接主管')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '组织架构信息',
                'verbose_name_plural': '组织架构管理',
                'ordering': ['department__dept_code', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='TestBusinessApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_code', models.CharField(default='TEST2024001', help_text='用于和业务模块的原始单据进行关联索引', max_length=100, unique=True, verbose_name='单据编号')),
                ('business_type', models.CharField(max_length=50, verbose_name='业务类型')),
                ('application_title', models.CharField(max_length=200, verbose_name='申请标题')),
                ('workflow_code', models.CharField(default='TEST_FLOW', help_text='请输入已定义的流程 Code，如：EXPENSE_FLOW', max_length=50, verbose_name='流程编码')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='申请金额')),
                ('business_description', models.TextField(blank=True, null=True, verbose_name='业务描述')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approve_flow.department', verbose_name='申请部门')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '测试业务申请',
                'verbose_name_plural': '测试业务申请',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approve_flow.department', verbose_name='所属部门')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approve_flow.roledefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色分配',
                'verbose_name_plural': '用户角色分配管理',
                'ordering': ['user__username', 'department__dept_code', 'role__role_code'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='审批环节', max_length=100, verbose_name='环节名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='步骤序号')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='审批层级')),
                ('approve_mode', models.CharField(choices=[('ANY', '任一人审批 (或签)'), ('ALL', '全体共同审批 (会签)'), ('NOTIFY', '仅通知 (无需审批)')], default='ANY', max_length=10, verbose_name='审批模式')),
                ('superior_approve', models.BooleanField(default=False, verbose_name='由直接主管审批')),
                ('dept_mgr_approve', models.BooleanField(default=False, verbose_name='由部门主管审批')),
                ('amount_control', models.BooleanField(default=False, verbose_name='启用金额控制')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('permission_tag', models.CharField(blank=True, default='basic_approval', max_length=100, null=True, verbose_name='权限标签')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('roles', models.ManyToManyField(blank=True, to='approve_flow.roledefinition', verbose_name='审批角色')),
                ('specific_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='指定审批人')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approve_flow.approveworkflow')),
            ],
            options={
                'verbose_name': '审批流程步骤',
                'verbose_name_plural': '审批流程步骤',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approve_flow.workflowstep', verbose_name='原始配置步骤'),
        ),
        migrations.AddIndex(
            model_name='flowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='approve_flo_content_0b3908_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeapprover',
            unique_together={('node', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userroleassignment',
            unique_together={('user', 'role', 'department')},
        ),
    ]
