# Generated by Django 6.0.2 on 2026-02-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approve_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approveworkflow',
            name='remove_duplicate_approvers',
            field=models.BooleanField(default=True, verbose_name='去重审批人'),
        ),
    ]
