# Generated by Django 6.0.2 on 2026-02-23 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0015_alter_clockedschedule_id_alter_crontabschedule_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.exmail.qq.com', max_length=255, verbose_name='SMTP服务器')),
                ('smtp_port', models.PositiveIntegerField(default=465, verbose_name='端口')),
                ('smtp_user', models.EmailField(max_length=254, verbose_name='发件账号')),
                ('smtp_password', models.CharField(max_length=255, verbose_name='授权码/密码')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='使用SSL')),
                ('from_name', models.CharField(default='审批系统', max_length=100, verbose_name='发件人显示名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '邮件服务器配置',
                'verbose_name_plural': '邮件服务器配置',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='zh-hans', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户配置',
                'verbose_name_plural': '用户配置',
            },
        ),
        migrations.CreateModel(
            name='UserScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='提醒任务名称')),
                ('description', models.TextField(verbose_name='任务详细说明')),
                ('recipients', models.TextField(help_text='接收人邮箱，多个请用逗号分隔', verbose_name='接收邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('crontab_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule', verbose_name='重复周期设置')),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_metadata', to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': '用户定时任务',
                'verbose_name_plural': '用户定时任务',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/%d/', verbose_name='附件文件')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api_services.userscheduledtask')),
            ],
        ),
    ]
