# Generated by Django 6.0.2 on 2026-02-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置名称')),
                ('db_type', models.CharField(choices=[('sqlite', 'SQLite'), ('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle')], default='sqlite', max_length=50, verbose_name='数据库类型')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='主机地址')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='端口')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('database_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='数据库名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '数据库连接配置',
                'verbose_name_plural': '数据库连接配置',
            },
        ),
    ]
