# Generated by Django 6.0.2 on 2026-02-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0002_dbconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconfig',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SQLite文件路径'),
        ),
    ]
