# Generated by Django 6.0.2 on 2026-02-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0003_dbconfig_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('AUTO-FIXED', 'Auto-Fixed')], max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('result_summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Skill Execution Log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
