# Generated by Django 6.0.2 on 2026-02-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0004_skillexecutionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillexecutionlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Skill Execution Log', 'verbose_name_plural': 'Skill Execution Log'},
        ),
    ]
