# Generated by Django 6.0.2 on 2026-02-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0005_alter_skillexecutionlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillexecutionlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Skill Execution Log', 'verbose_name_plural': '技能执行日志'},
        ),
    ]
