# Generated by Django 6.0.2 on 2026-02-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0007_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='base_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Base URL (if applicable)'),
        ),
    ]
