# Generated by Django 6.0.2 on 2026-02-26 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0008_apikey_base_url'),
        ('django_celery_beat', '0021_alter_crontabschedule_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API Key', 'verbose_name_plural': '接口密钥'},
        ),
        migrations.AddField(
            model_name='userscheduledtask',
            name='interval',
            field=models.PositiveIntegerField(default=1, verbose_name='间隔数值'),
        ),
        migrations.AddField(
            model_name='userscheduledtask',
            name='interval_period',
            field=models.CharField(blank=True, choices=[('Minutes', '分钟'), ('Hours', '小时'), ('Days', '天')], max_length=20, null=True, verbose_name='间隔单位'),
        ),
        migrations.AddField(
            model_name='userscheduledtask',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='是否循环执行'),
        ),
        migrations.AddField(
            model_name='userscheduledtask',
            name='period_type',
            field=models.CharField(blank=True, choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], max_length=20, null=True, verbose_name='周期单位'),
        ),
        migrations.AddField(
            model_name='userscheduledtask',
            name='plan_type',
            field=models.CharField(choices=[('interval', '固定间隔'), ('period', '固定周期'), ('specdate', '指定日期'), ('realtime', '实时')], default='interval', max_length=20, verbose_name='调度类型'),
        ),
        migrations.AddField(
            model_name='userscheduledtask',
            name='spec_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='指定执行时间'),
        ),
        migrations.AlterField(
            model_name='userscheduledtask',
            name='crontab_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule', verbose_name='重复周期设置'),
        ),
    ]
