# Generated by Django 6.0.2 on 2026-02-26 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0009_alter_apikey_options_userscheduledtask_interval_and_more'),
        ('django_celery_beat', '0022_alter_crontabschedule_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscheduledtask',
            name='interval_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.intervalschedule', verbose_name='Interval间隔设置'),
        ),
        migrations.AlterField(
            model_name='userscheduledtask',
            name='crontab_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule', verbose_name='Crontab周期设置'),
        ),
    ]
