# Generated by Django 6.0.2 on 2026-02-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0010_userscheduledtask_interval_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscheduledtask',
            name='task_name',
            field=models.CharField(default='ai_subscription.tasks.task_generate_ai_report', max_length=255, verbose_name='Celery任务路径'),
        ),
        migrations.AlterField(
            model_name='userscheduledtask',
            name='title',
            field=models.CharField(max_length=200, verbose_name='任务名称'),
        ),
    ]
