# Generated by Django 6.0.2 on 2026-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0011_userscheduledtask_task_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscheduledtask',
            name='recipients',
        ),
        migrations.AddField(
            model_name='userscheduledtask',
            name='task_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='任务参数（JSON格式）'),
        ),
        migrations.AlterField(
            model_name='userscheduledtask',
            name='interval_period',
            field=models.CharField(blank=True, choices=[('Seconds', '秒'), ('Minutes', '分钟'), ('Hours', '小时'), ('Days', '天')], max_length=20, null=True, verbose_name='间隔单位'),
        ),
        migrations.AlterField(
            model_name='userscheduledtask',
            name='period_type',
            field=models.CharField(blank=True, choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月'), ('quarterly', '季度'), ('yearly', '每年'), ('realtime', '实时')], max_length=20, null=True, verbose_name='周期单位'),
        ),
        migrations.AlterField(
            model_name='userscheduledtask',
            name='task_name',
            field=models.CharField(choices=[('api_services.tasks.task_email_reminder', 'task_email_reminder')], default='api_services.tasks.task_email_reminder', max_length=255, verbose_name='Celery任务路径'),
        ),
    ]
