# Generated by Django 6.0.2 on 2026-02-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0012_remove_userscheduledtask_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscheduledtask',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间'),
        ),
    ]
