# Generated by Django 6.0.2 on 2026-02-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0013_userscheduledtask_last_run_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'verbose_name': '任务附件', 'verbose_name_plural': '任务附件'},
        ),
    ]
