# Generated by Django 6.0.2 on 2026-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0014_alter_taskattachment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='filename',
            field=models.CharField(default=None, max_length=255, verbose_name='原始文件名'),
        ),
    ]
