# Generated by Django 6.0.2 on 2026-02-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0016_alter_taskattachment_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='任务名称/标识')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failed'), ('STARTED', 'Started')], max_length=50, verbose_name='执行状态')),
                ('result_summary', models.TextField(blank=True, null=True, verbose_name='结果摘要')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='api_services.userscheduledtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务执行日志',
                'verbose_name_plural': '任务执行日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
