# Generated by Django 6.0.2 on 2026-02-28 03:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0017_taskexecutionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscheduledtask',
            name='task_name',
            field=models.CharField(choices=[('api_services.tasks.run_skill_task', 'Execute skill function by name (system tasks for ai workbench).'), ('api_services.tasks.task_email_reminder', 'task_email_reminder')], default='api_services.tasks.task_email_reminder', max_length=255, verbose_name='Celery任务路径'),
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('role', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
