# Generated by Django 6.0.2 on 2026-02-28 05:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_conversations(apps, schema_editor):
    AIChatConversation = apps.get_model('api_services', 'AIChatConversation')
    AIChatMessage = apps.get_model('api_services', 'AIChatMessage')
    db_alias = schema_editor.connection.alias

    conv_cache = {}
    messages = AIChatMessage.objects.using(db_alias).all().order_by('created_at')

    for msg in messages:
        legacy_cid = getattr(msg, 'legacy_conversation_id', None)
        if not legacy_cid:
            continue

        if legacy_cid not in conv_cache:
            conv_cache[legacy_cid] = AIChatConversation.objects.using(db_alias).create(
                id=legacy_cid,
                user=msg.user,
                title=(msg.text or '')[:50],
            )

        conv = conv_cache[legacy_cid]
        msg.conversation = conv
        msg.save(update_fields=['conversation'])

    for conv in conv_cache.values():
        qs = AIChatMessage.objects.using(db_alias).filter(conversation=conv).order_by('created_at')
        count = qs.count()
        last_msg = qs.last()
        conv.message_count = count
        conv.last_message_at = last_msg.created_at if last_msg else None
        conv.last_role = last_msg.role if last_msg else ''
        conv.last_text = last_msg.text if last_msg else ''
        conv.save(update_fields=['message_count', 'last_message_at', 'last_role', 'last_text'])


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0018_alter_userscheduledtask_task_name_aichatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscheduledtask',
            name='task_name',
            field=models.CharField(choices=[('api_services.tasks.run_skill_task', 'Execute skill function by name (system tasks for AI workbench).'), ('api_services.tasks.task_email_reminder', 'task_email_reminder')], default='api_services.tasks.task_email_reminder', max_length=255, verbose_name='Celery任务路径'),
        ),
        migrations.RenameField(
            model_name='aichatmessage',
            old_name='conversation_id',
            new_name='legacy_conversation_id',
        ),
        migrations.CreateModel(
            name='AIChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_role', models.CharField(blank=True, default='', max_length=20)),
                ('last_text', models.TextField(blank=True, default='')),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chat Conversation',
                'verbose_name_plural': 'AI Chat Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, db_column='conversation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api_services.aichatconversation'),
        ),
        migrations.RunPython(seed_conversations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='aichatmessage',
            name='legacy_conversation_id',
        ),
    ]
