# Generated by Django 6.0.2 on 2026-02-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0019_remove_aichatmessage_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认配置'),
        ),
    ]
