# Generated by Django 6.0.2 on 2026-02-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0020_emailconfig_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='使用TLS'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='use_ssl',
            field=models.BooleanField(default=False, verbose_name='使用SSL'),
        ),
    ]
