# Generated by Django 6.0.2 on 2026-03-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0022_systemprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
