# Generated by Django 6.0.2 on 2026-03-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0025_conversationmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='system_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='api_services.systemprompt', verbose_name='系统提示词'),
        ),
        migrations.AlterField(
            model_name='conversationmode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
