# Generated by Django 6.0.2 on 2026-03-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0026_aichatmessage_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatconversation',
            name='chat_memeory',
            field=models.JSONField(blank=True, default=list, verbose_name='对话记忆（JSON格式）'),
        ),
    ]
