# Generated by Django 6.0.2 on 2026-03-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0027_aichatconversation_chat_memeory'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatconversation',
            name='key_words',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='对话关键词'),
        ),
    ]
