# Generated by Django 6.0.2 on 2026-03-02 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0028_aichatconversation_key_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aichatconversation',
            old_name='chat_memeory',
            new_name='chat_memory',
        ),
    ]
