# Generated by Django 6.0.2 on 2026-03-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0029_rename_chat_memeory_aichatconversation_chat_memory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aichatconversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'AI Chat Conversation', 'verbose_name_plural': 'AI-会话'},
        ),
        migrations.AlterModelOptions(
            name='aichatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'AI Chat Message', 'verbose_name_plural': 'AI-会话消息'},
        ),
        migrations.AlterModelOptions(
            name='conversationmode',
            options={'ordering': ['code'], 'verbose_name': 'AI conversation mode', 'verbose_name_plural': 'AI-对话模式'},
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用途分类'),
        ),
    ]
