# Generated by Django 6.0.2 on 2026-02-23 02:41

import ai_subscription.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='订阅人姓名')),
                ('user_email', models.EmailField(max_length=254, verbose_name='接收邮箱')),
                ('report_title', models.CharField(error_messages={'unique': '该简报名称已存在，请换一个名字。'}, max_length=200, unique=True, verbose_name='简报名称')),
                ('keywords', models.CharField(max_length=500, verbose_name='关注关键词')),
                ('description', models.TextField(error_messages={'required': '该简报名称已存在，请换一个名字。'}, verbose_name='详细内容描述')),
                ('period', models.CharField(choices=[('daily', '每日汇总'), ('weekly', '每周复盘'), ('monthly', '每月总结'), ('quarterly', '季度深挖'), ('yearly', '年度汇报'), ('realtime', '实时推送')], default='daily', max_length=20, verbose_name='生成周期')),
                ('send_time', models.TimeField(default='09:00', verbose_name='推送时间')),
                ('format_type', models.CharField(max_length=50, verbose_name='输出格式模板')),
                ('subscription_date', models.DateField(default=django.utils.timezone.now, help_text='您可以手动调整此订阅的起始日期', verbose_name='订阅日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次运行时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'AI subscriptions',
                'ordering': ['-subscription_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='简报生成时间')),
                ('recipients', models.TextField(verbose_name='接收人列表')),
                ('content_markdown', models.TextField(verbose_name='简报格式文本')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='内容摘要')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='ai_subscription.subscription', verbose_name='所属订阅')),
            ],
            options={
                'verbose_name': 'report history',
                'verbose_name_plural': 'report histories',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ai_subscription.models.get_subscription_upload_path, verbose_name='参考文档')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ai_subscription.subscription')),
            ],
            options={
                'verbose_name': 'reference document',
                'verbose_name_plural': 'reference documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='接收人邮箱')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='接收人姓名')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_list', to='ai_subscription.subscription')),
            ],
            options={
                'verbose_name': 'subscription recipient',
                'verbose_name_plural': 'subscription recipients',
                'unique_together': {('subscription', 'email')},
            },
        ),
    ]
